version: 2

models:
  - name: dim_patients
    description: Dimension table containing patient demographics and identifiers.
    columns:
      - name: patient_id
        description: Unique identifier for each patient.
        tests:
          - not_null
          - unique
      - name: first_name
        description: Patient first name (lowercased).
      - name: last_name
        description: Patient last name (lowercased).
      - name: birthdate
        description: Date of birth.
        tests:
          - not_null
      - name: gender
        description: Gender (M or F).
        tests:
          - accepted_values:
              values: ['M', 'F']
      - name: race
        description: Self-reported race category.
      - name: zip
        description: ZIP code of residence.

  - name: dim_providers
    description: Dimension table containing provider identifiers and specialties.
    columns:
      - name: provider_id
        description: Unique identifier for the provider.
        tests:
          - not_null
          - unique
      - name: provider_name
        description: Full name of the provider.
      - name: specialty
        description: Medical specialty of the provider.
        tests:
          - accepted_values:
              values: ["Internal Medicine", "Emergency", "Cardiology", "Pediatrics", "Orthopedics"]
      - name: npi
        description: National Provider Identifier (as string).

  - name: dim_locations
    description: Dimension table describing facility and unit locations.
    columns:
      - name: location_id
        description: Unique identifier for the location.
        tests:
          - not_null
          - unique
      - name: facility_name
        description: Name of the medical facility.
      - name: unit
        description: Unit of care within the facility.
        tests:
          - accepted_values:
              values: ["ED", "ICU", "Med-Surg", "Outpatient", "Radiology"]
      - name: city
        description: City where the facility is located.
      - name: state
        description: US state abbreviation.

  - name: fct_admissions
    description: Fact table for hospital admissions enriched with dimension details and derived metrics.
    columns:
      - name: admission_id
        description: Unique identifier for the admission event.
        tests:
          - not_null
          - unique
          - no_overlapping_admissions:
              patient_id_col: patient_id
              admit_col: admit_date
              discharge_col: discharge_date
            severity: warn

      - name: admit_date
        description: Date of hospital admission.
        tests:
          - not_null

      - name: discharge_date
        description: Date of hospital discharge.
        tests:
          - not_null
          - discharge_after_admit:
              admit_col: admit_date
              discharge_col: discharge_date

      - name: length_of_stay
        description: Number of days between admission and discharge.
        tests:
          - not_null

      - name: admission_type
        description: Classification of the admission event.
        tests:
          - accepted_values:
              values: ["Emergency", "Elective", "Urgent"]

      - name: stay_category
        description: Categorized length of stay (Short, Medium, Long).
        tests:
          - accepted_values:
              values: ["Short", "Medium", "Long"]

      - name: admission_number
        description: Sequential number of the admission per patient.
        tests:
          - not_null

      - name: days_since_last_admission
        description: Days between this admission and previous discharge for the same patient.

      - name: readmission_flag
        description: 1 if admitted within 30 days of previous discharge, else 0.
        tests:
          - accepted_values:
              values: [0, 1]

      - name: patient_id
        description: Foreign key to dim_patients.
        tests:
          - not_null
          - fact_references_dimension:
              fact_model: fct_admissions
              dim_model: dim_patients
              fact_key: patient_id
              dim_key: patient_id

      - name: provider_id
        description: Foreign key to dim_providers.
        tests:
          - not_null

      - name: location_id
        description: Foreign key to dim_locations.
        tests:
          - not_null

