name: dbt build & docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./.profiles
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dbt core + DuckDB adapter ONLY (don't pip-install dbt-utils)
      - name: Install dbt
        run: |
          pip install "dbt-core==1.7.13" "dbt-duckdb==1.7.2"
          dbt --version

      # Minimal DuckDB profile for CI
      - name: Create dbt profile
        run: |
          mkdir -p ./.profiles
          cat > ./.profiles/profiles.yml <<'YML'
          healthcare:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: "ci.duckdb"
          YML

      # Sanity check the project + profile
      - name: dbt debug
        run: dbt debug --profiles-dir ./.profiles --project-dir .

      - name: dbt deps
        run: dbt deps

      - name: dbt seed (optional)
        run: dbt seed --full-refresh || echo "No seeds present"

      - name: List models (visibility)
        run: dbt ls

      - name: dbt build
        run: dbt build --fail-fast

      - name: Generate docs
        run: dbt docs generate --target-path docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-pages:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
